const DEFAULT_VALUE = 0
const DEFAULT_TITLE = 'No Title'

const TITLE_CARD_OVERVIEW = 'Products Statistics overview'

const MAX_CARD_WITDH = 350
const MAX_CARD_HEIGHT = 350
const FILE_EXTENSION = '.webp'

export { MAX_CARD_HEIGHT, DEFAULT_TITLE, DEFAULT_VALUE, MAX_CARD_WITDH, TITLE_CARD_OVERVIEW, FILE_EXTENSION }
