const BACKEND_BASE_API_URL = import.meta.env.VITE_BACKEND_BASE_API_URL
const BACKEND_ADMIN_PATH = import.meta.env.VITE_ADMIN_API_PATH
const APP_CLIENT_PATH_HOME = '/home'

const DEFAULT_PAGE_SIZE = 10

export { BACKEND_BASE_API_URL, APP_CLIENT_PATH_HOME, BACKEND_ADMIN_PATH, DEFAULT_PAGE_SIZE }
